[build]
  backend = "cd backend && npm install && npm run build"
  frontend = "cd frontend && npm install && npm run build"

[[services]]
  name = "backend"
  start = "cd backend && npm start"
  build = "cd backend && npm run build"

[[services]]
  name = "frontend"
  start = "cd frontend && npm start"
  build = "cd frontend && npm run build"
